# Cross compiling for raspberry pi zero armv6 architecture.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)


set(CMAKE_FIND_ROOT_PATH $ENV{CROSS_SYSROOT})
set(CMAKE_C_COMPILER $ENV{CROSS_BIN_PATH}/armv6-rpi-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER $ENV{CROSS_BIN_PATH}/armv6-rpi-linux-gnueabihf-g++)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
